# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 111eae7634689eea1523759684643d2fef420fcd61a891e7718216e19e438003481a81b95f4b1bf863e6de2e34e4ceb76a312d59fe3ccc6bbd2af732101b8bb8

test:
  secret_key_base: 505b9b8214c578859c0867bd8bad376ae8112789bdf8882a0fdb98420d86da8a129d26be25f428963786a9fa3c6c042c0fffaa12acd79df44dd23e6305242b0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
